aws:
  region: ${AWS_REGION}
  bucketName: ${AWS_S3_BUCKET}
  s3AccessKey: ${AWS_ACCESS_KEY}
  s3SecretKey: ${AWS_SECRET_KEY}
  base-url: ${AWS_S3_BASE_URL}


spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false