CREATE TABLE guest_books(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    title varchar(100) NOT NULL,
    content varchar(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    image_url varchar(200) NOT NULL
);