name: App deploy

on:
  workflow_dispatch:

jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'termurin'

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: Build Docker image
        run: docker build -t fm-app:lastest .

      ## ECR이랑 이미지 형식 지정
      ## ECR 주소
      - name: Set environment variables
        run: |
          echo "ECR_REPOSITORY=038899712225.dkr.ecr.ap-northeast-2.amazonaws.com/guestbook/guest-book" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')-${GITHUB_SHA::8}" >> $GITHUB_ENV

      # 태깅 시작,태깅 형식이랑 latest로 두번 태킹
      - name: Tag Docker image
        run: |
          docker tag fm-app:latest ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker tag fm-app:latest ${{ env.ECR_REPOSITORY }}:latest

      # AWS 연결
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_DEPLOY_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # task definition json 다운
      ## fm-app이 task definiton 연결하는 걸듯
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition guest-book --query taskDefinition > task-definition.json

      # 새로운 task-definition 생성
      - name: Update task definition with new image
        id : render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: ${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
#          environment-variables: |
#            SPRING_PROFILES_ACTIVE=dev
#            HELLO=world

      # task definition 내용 출력
      - name: Print task definition
        run: |
          echo ${{ steps.render-task-def.outputs.task-definition }}
          cat ${{ steps.render-task-def.outputs.task-definition }}

      # ECS 서비스 환경섨정 # 기존 클러스터와 서비스
      - name: Set ECS environment variables
        run: |
          echo "ECS_CLUSTER=happy-tiger-m4xoy2" >> $GITHUB_ENV
          echo "ECS_SERVICE=guest-book-service-l77n8y6p" >> $GITHUB_ENV

      # ECS 서비스에 배포
      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true

      #  배포 확인
      - name: Verify deployment
        run: |
          echo "Verifying deployment..."
          SERVICE_STATUS=$(aws ecs describe-services --cluster ${{ env.ECS_CLUSTER }} --services ${{ env.ECS_SERVICE }} --query 'services[0].status' --output text)
          
          if [ "$SERVICE_STATUS" = "ACTIVE" ]; then
            echo "Deployment successful! Service is active."
          else
            echo "Deployment may have issues. Service status: $SERVICE_STATUS"
            exit 1
          fi
          

        
