name: CI

on:
  push:
    branches:
      - main
env:
  SPRING_PROFILES_ACTIVE: test # 필수
jobs:
  test-aws-connection:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: |
          chmod +x ./gradlew
          ./gradlew test